// Code generated by "stringer -type Case -linecomment"; DO NOT EDIT.

package opt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Camel-0]
	_ = x[Kebab-1]
	_ = x[LowerCamel-2]
	_ = x[Snake-3]
	_ = x[Lower-4]
	_ = x[Upper-5]
}

const _Case_name = "CamelCasekebab-caselowerCamelsnake_case (default)lowerUPPER"

var _Case_index = [...]uint8{0, 9, 19, 29, 49, 54, 59}

func (i Case) String() string {
	if i < 0 || i >= Case(len(_Case_index)-1) {
		return "Case(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Case_name[_Case_index[i]:_Case_index[i+1]]
}
