// Code generated by "stringer -type PadPosition -linecomment"; DO NOT EDIT.

package opt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Beginning-0]
	_ = x[BeforeName-1]
	_ = x[AfterName-2]
	_ = x[End-3]
}

const _PadPosition_name = "BeginningBefore NameAfter NameEnd (default)"

var _PadPosition_index = [...]uint8{0, 9, 20, 30, 43}

func (i PadPosition) String() string {
	if i < 0 || i >= PadPosition(len(_PadPosition_index)-1) {
		return "PadPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PadPosition_name[_PadPosition_index[i]:_PadPosition_index[i+1]]
}
