// Code generated by "stringer -trimprefix Pos -type PadPosition"; DO NOT EDIT.

package name

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PosStart-0]
	_ = x[PosBeforeName-1]
	_ = x[PosAfterName-2]
	_ = x[PosEnd-3]
}

const _PadPosition_name = "StartBeforeNameAfterNameEnd"

var _PadPosition_index = [...]uint8{0, 5, 15, 24, 27}

func (i PadPosition) String() string {
	if i < 0 || i >= PadPosition(len(_PadPosition_index)-1) {
		return "PadPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PadPosition_name[_PadPosition_index[i]:_PadPosition_index[i+1]]
}
